version: '3'
services:
  mongo:
    image: "mongo:latest"
    volumes:
     - "./data:/data/db"
    ports:
     - "27017:27017"
  poussetaches:
    image: "poussetaches/poussetaches:latest"
    volumes:
     - "${DATA_DIR}/poussetaches:/app/poussetaches_data"
    environment:
     - POUSSETACHES_AUTH_KEY=${POUSSETACHES_AUTH_KEY}
    ports:
     - "7991:7991"
