username: 'username'
name: 'You Name'
domain: 'your-domain.tld'
https: true
summary: 'your summary'
icon_url: 'https://you-avatar-url'
#favicon_url: '/static/favicon.png'
#pass: '<bcrypt password hash>'
#profile_metadata:
#    name1: 'value'
#    name2: 'value2'
hide_following: true
#theme:
#    style: "light" #or "dark"
#    color: "#1d781d" # (green, default for light)
          # "#33ff00"   (purple, default for dark)
